### ISSUE TITLE
控制器添加注释Swagger无法运行Bug

### ISSUE THREAD

**Issue by Fixoo** [MonkSoul/Furion#158]
Net 6
版本：Furion.Pure 3.0.6
操作步骤：
1、在头部添加注释Swagger运行报错

    /// <summary>
    /// TODO
    /// </summary>
    [ApiController]
    [Route("[controller]/V1")]
    public class TestController : ControllerBase
2、在下面添加注释Swagger运行正常

    [ApiController]
    [Route("[controller]")]
    /// <summary>
    /// TODO
    /// </summary>
    public class TestController : ControllerBase
错误信息：
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NotSupportedException: Collection was of a fixed size.
         at System.SZArrayHelper.Add[T](T value)
         at Swashbuckle.AspNetCore.SwaggerGen.XmlCommentsDocumentFilter.Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
         at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by Fixoo** [comment]
1
